### 

POST http://localhost:8080/admin/reset HTTP/1.1


### 

POST http://localhost:8080/api/refresh HTTP/1.1
Content-Type: application/json
Authorization: Bearer 9a61ac00235f40c3cffe12a3b9206f89a316fb99af10578f85f918e27e03eac3
